### ISSUE TITLE
Repeated "Warning: TF_REPEATED_DATA" messages on ROS Noetic

### ISSUE THREAD

**Issue by jabb1123** [LORD-MicroStrain/microstrain_inertial_driver_common#42]
Using the microstrain node with ROS Noetic produce many Warning: TF_REPEATED_DATA messages that flood the console. From the discussion at [#467](https://github.com/ros/geometry2/issues/467) from geometry2, the current solution is to make sure you don't publish the TF with the same timestamp. Looking at [publishers.cpp|212](https://github.com/LORD-MicroStrain/microstrain_inertial_driver_common/blob/ddd158f945f6bda31cf7915bece069ac950f56cc/src/publishers.cpp#L212), it seems like the only requirement to publish a new TF is that the filter_relative_odom_pub_ be updated. 

However, [handleFilterPositionLlhUncertainty](https://github.com/LORD-MicroStrain/microstrain_inertial_driver_common/blob/ddd158f945f6bda31cf7915bece069ac950f56cc/src/publishers.cpp#L640) does not update the timestamp for the Transform while updating the covariances, producing multiple TFs with the same data. 

Two ways to tackle this:
1. Add a second check to the TF broadcast that checks if the TF header timestamp is different. (requires storing the old value) 
2. Update the TF header in handleFilterPositionLlhUncertainty in addition to the odom header.

**Comment by weiying-robotic** [comment]
I also encountered this issue and hopefully, someone can post a patch code for it. Thanks!

**Comment by antoniskara** [comment]
Same here. Anyone is up to a solution?

**Comment by hanlinniu** [comment]
Hello, have you solved this problem?

**Comment by hanlinniu** [comment]
> c

Hello weiying, have you solved this problem?

**Comment by robbiefish** [comment]
This should be fixed in the most recent 3.0.0 and 4.0.0 releases
