### ISSUE TITLE
Cannot set imu_data_rate >100Hz for CV7

### ISSUE THREAD

**Issue by shahyaan** [LORD-MicroStrain/microstrain_inertial_driver_common#56]
Hi, 

I'm trying to set the imu_data_rate to 250 Hz in my parameter file and I keep getting the following error
'terminate called after throwing an instance of 'mscl::Error_Communication'. The IMU is capable of data rates up to 1kHz, so I'm not sure why there seems to be a 100Hz limit built into the ROS driver. Can anyone assist me with diagnosing this problem?

Thanks

**Comment by robbiefish** [comment]
Hi @shahyaan, please open a bug report issue on https://github.com/LORD-MicroStrain/microstrain_inertial and fill out as much information as you can from the form, that would help me diagnose the problem, thanks
